# Generated by Django 3.1.5 on 2021-01-25 08:27

from django.db import migrations, models
import jsonfield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Poi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lat', models.FloatField()),
                ('lon', models.FloatField()),
                ('category', models.CharField(choices=[('vg', 'verygood'), ('gg', 'good'), ('bb', 'bad')], max_length=2)),
                ('geojson', jsonfield.fields.JSONField()),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
    ]
