# Generated by Django 3.1.5 on 2021-01-25 08:29

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poi',
            name='geojson',
            field=jsonfield.fields.JSONField(blank=True, null=True),
        ),
    ]
