# Generated by Django 3.1.5 on 2021-01-25 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0002_auto_20210125_1329'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poi',
            name='category',
            field=models.CharField(choices=[('verygood', 'verygood'), ('good', 'good'), ('bad', 'bad')], max_length=20),
        ),
    ]
